name: abstract_widget
description: Generic widget that builds itself depending on the derived class of current value.
version: 1.0.0
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
